# Generated by Django 5.1.4 on 2024-12-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_site', '0003_alter_story_story_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_images/'),
        ),
    ]
