# Generated by Django 5.1.4 on 2024-12-27 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_site', '0005_alter_postlike_post_alter_postlike_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_site.hashtag'),
        ),
    ]
